### ISSUE TITLE
Django example

### ISSUE THREAD

**Issue by samrose** [datakurre/setup.nix#9]
Can you give some pointers for creating a package around Django? I would be happy to test, verify and PR a working example of the same, but could use some pointers on it if you can advise?

To clarify I am looking to create a package like https://github.com/datakurre/setup.nix/tree/master/examples/package that I can include in a nixos iso build I am working on

**Comment by datakurre** [comment]
@samrose Sorry for delay. Could you give more context on what you'd like to achieve, because some versions of Django are already packaged in NixOS.

If you only want something like "virtualenv" with django-packages, then https://github.com/datakurre/setup.nix/tree/master/examples/env could be better example.

setup.nix-packaged stuff can be included into nixos build with something like

```nix
{
  environment = [
  (import ./path/setup.nix { inherit pkgs; }).target
];
}
```
where `target` is `build` for a Python package or `env` for whole environment (like virtualenv with everything from generated requirements.nix).

**Comment by samrose** [comment]
@datakurre I am actually thinking here of packaging the deployment of the app (like instead of a remote NixOps configuration, to package a django project app source code, and deploy it via a package. Is that an appropriate use of setup.nix?

**Comment by datakurre** [comment]
@samrose It’s the same kind usecase, why I create this. I’ll provide an example.
